# Generated by Django 4.0.3 on 2022-04-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date_added',
        ),
    ]
